[relaychain]
chain = "paseo-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 1000
chain = "dev"

[[parachains.collators]]
name = "collator-01"
command = "./target/release/ideal-nw-node"
