[relaychain]
default_command = "polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 9944

[[relaychain.nodes]]
name = "bob"
validator = true
ws_port = 9955

[[parachains]]
id = 2000

[[parachains.collators]]
name = "alice"
ws_port = 9988
command = "./target/release/ideal-nw-node"
